/** categories.icon uchun ruxsat etilgan lucide nomlari — src/components/shared/category-icon.tsx bilan bir xil */
export const CATEGORY_ICONS = [
  "laptop",
  "shopping-cart",
  "megaphone",
  "palette",
  "calculator",
  "car",
  "truck",
  "bike",
  "hard-hat",
  "wrench",
  "zap",
  "droplet",
  "cog",
  "car-front",
  "utensils",
  "headset",
  "briefcase",
  "graduation-cap",
  "stethoscope",
  "sparkles",
  "shield",
  "scissors",
  "scissors-line-dashed",
  "factory",
  "wheat",
  "more-horizontal",
] as const;
