-- ISH.UZ · 0012 · ma'lumotnoma seed (scripts/gen/seed_reference.py orqali yaratilgan)

insert into public.languages (code, name_uz, name_ru, sort_order) values
  ('uz', 'O''zbek tili', 'Узбекский', 0),
  ('ru', 'Rus tili', 'Русский', 10),
  ('en', 'Ingliz tili', 'Английский', 20),
  ('tr', 'Turk tili', 'Турецкий', 30),
  ('kk', 'Qozoq tili', 'Казахский', 40),
  ('tg', 'Tojik tili', 'Таджикский', 50),
  ('ko', 'Koreys tili', 'Корейский', 60),
  ('zh', 'Xitoy tili', 'Китайский', 70),
  ('de', 'Nemis tili', 'Немецкий', 80),
  ('ar', 'Arab tili', 'Арабский', 90),
  ('fr', 'Fransuz tili', 'Французский', 100)
on conflict (code) do update set name_uz = excluded.name_uz, name_ru = excluded.name_ru;

insert into public.benefits (code, name_uz, name_ru, kind, sort_order) values
  ('food', 'Ovqat', 'Питание', 'benefit', 0),
  ('transport', 'Transport', 'Транспорт', 'benefit', 10),
  ('phone_expenses', 'Telefon xarajati', 'Оплата связи', 'benefit', 20),
  ('bonus', 'Bonus', 'Бонусы', 'benefit', 30),
  ('kpi', 'KPI', 'KPI', 'benefit', 40),
  ('dormitory', 'Yotoqxona', 'Общежитие', 'benefit', 50),
  ('uniform', 'Forma', 'Форма', 'benefit', 60),
  ('training', 'O''qitish', 'Обучение', 'benefit', 70),
  ('career_growth', 'Karyera o''sishi', 'Карьерный рост', 'benefit', 80),
  ('flexible_hours', 'Moslashuvchan grafik', 'Гибкий график', 'benefit', 90),
  ('health_insurance', 'Tibbiy sug''urta', 'Медицинская страховка', 'benefit', 100),
  ('fuel', 'Yoqilg''i', 'ГСМ', 'benefit', 110),
  ('labor_contract', 'Mehnat shartnomasi', 'Трудовой договор', 'official_term', 120),
  ('tax_registration', 'Soliq rasmiylashtirish', 'Налоговое оформление', 'official_term', 130),
  ('card_salary', 'Oylik karta orqali', 'Зарплата на карту', 'official_term', 140),
  ('social_package', 'Ijtimoiy paket', 'Социальный пакет', 'official_term', 150),
  ('paid_leave', 'Ta''til', 'Оплачиваемый отпуск', 'official_term', 160),
  ('sick_leave', 'Kasallik varaqasi', 'Больничный', 'official_term', 170),
  ('official_bonus', 'Rasmiy bonus', 'Официальные премии', 'official_term', 180)
on conflict (code) do update set name_uz = excluded.name_uz, name_ru = excluded.name_ru, kind = excluded.kind;

insert into public.categories (slug, name_uz, name_ru, icon, sort_order, portfolio_recommended) values
  ('it', 'IT va dasturlash', 'IT и программирование', 'laptop', 0, true),
  ('sales', 'Savdo', 'Продажи', 'shopping-cart', 10, false),
  ('marketing', 'Marketing va SMM', 'Маркетинг и SMM', 'megaphone', 20, true),
  ('design', 'Dizayn va media', 'Дизайн и медиа', 'palette', 30, true),
  ('finance', 'Buxgalteriya va moliya', 'Бухгалтерия и финансы', 'calculator', 40, false),
  ('driver', 'Haydovchi', 'Водитель', 'car', 50, false),
  ('logistics', 'Logistika va ombor', 'Логистика и склад', 'truck', 60, false),
  ('courier', 'Kuryer va yetkazib berish', 'Курьер и доставка', 'bike', 70, false),
  ('construction', 'Qurilish', 'Строительство', 'hard-hat', 80, true),
  ('craftsman', 'Usta va ta''mirlash', 'Мастер и ремонт', 'wrench', 90, true),
  ('electrician', 'Elektrik', 'Электрик', 'zap', 100, false),
  ('plumber', 'Santexnik', 'Сантехник', 'droplet', 110, false),
  ('mechanic', 'Mexanik va texnik', 'Механик и техник', 'cog', 120, false),
  ('auto_service', 'Avtoservis', 'Автосервис', 'car-front', 130, false),
  ('restaurant', 'Restoran va kafe', 'Ресторан и кафе', 'utensils', 140, false),
  ('call_center', 'Call-markaz va operator', 'Колл-центр и оператор', 'headset', 150, false),
  ('office', 'Ofis va boshqaruv', 'Офис и управление', 'briefcase', 160, false),
  ('education', 'Ta''lim', 'Образование', 'graduation-cap', 170, false),
  ('medicine', 'Tibbiyot', 'Медицина', 'stethoscope', 180, false),
  ('cleaning', 'Tozalik va uy xizmatlari', 'Уборка и домашний персонал', 'sparkles', 190, false),
  ('security', 'Xavfsizlik', 'Безопасность', 'shield', 200, false),
  ('sewing', 'Tikuvchilik', 'Швейное дело', 'scissors', 210, true),
  ('beauty', 'Go''zallik sohasi', 'Индустрия красоты', 'scissors-line-dashed', 220, true),
  ('production', 'Ishlab chiqarish', 'Производство', 'factory', 230, false),
  ('agriculture', 'Qishloq xo''jaligi', 'Сельское хозяйство', 'wheat', 240, false),
  ('other', 'Boshqa', 'Другое', 'more-horizontal', 250, false)
on conflict (slug) do update set name_uz = excluded.name_uz, name_ru = excluded.name_ru, icon = excluded.icon, sort_order = excluded.sort_order, portfolio_recommended = excluded.portfolio_recommended;

insert into public.subcategories (category_id, slug, name_uz, name_ru, sort_order)
select c.id, s.slug, s.name_uz, s.name_ru, s.sort_order from (values
  ('it', 'frontend', 'Frontend dasturchi', 'Frontend-разработчик', 0),
  ('it', 'backend', 'Backend dasturchi', 'Backend-разработчик', 10),
  ('it', 'fullstack', 'Full-stack dasturchi', 'Full-stack разработчик', 20),
  ('it', 'flutter', 'Flutter dasturchi', 'Flutter-разработчик', 30),
  ('it', 'android', 'Android dasturchi', 'Android-разработчик', 40),
  ('it', 'ios', 'iOS dasturchi', 'iOS-разработчик', 50),
  ('it', 'uiux', 'UI/UX dizayner', 'UI/UX дизайнер', 60),
  ('it', 'qa', 'QA / Tester', 'QA / Тестировщик', 70),
  ('it', 'devops', 'DevOps', 'DevOps', 80),
  ('it', 'support', 'IT support / tizim administratori', 'IT support / системный администратор', 90),
  ('it', 'data', 'Data analitik', 'Дата-аналитик', 100),
  ('it', '1c', '1C dasturchi', '1C-программист', 110),
  ('sales', 'seller', 'Sotuvchi', 'Продавец', 0),
  ('sales', 'consultant', 'Sotuvchi-konsultant', 'Продавец-консультант', 10),
  ('sales', 'cashier', 'Kassir', 'Кассир', 20),
  ('sales', 'agent', 'Savdo agenti', 'Торговый агент', 30),
  ('sales', 'merchandiser', 'Merchandayzer', 'Мерчандайзер', 40),
  ('sales', 'sales_manager', 'Sotuv menejeri', 'Менеджер по продажам', 50),
  ('sales', 'supervisor', 'Supervayzer', 'Супервайзер', 60),
  ('marketing', 'marketer', 'Marketolog', 'Маркетолог', 0),
  ('marketing', 'smm', 'SMM mutaxassis', 'SMM-специалист', 10),
  ('marketing', 'target', 'Targetolog', 'Таргетолог', 20),
  ('marketing', 'copywriter', 'Kopirayter', 'Копирайтер', 30),
  ('marketing', 'content', 'Kontent-meyker', 'Контент-мейкер', 40),
  ('marketing', 'mobilographer', 'Mobilograf', 'Мобилограф', 50),
  ('marketing', 'brand', 'Brend-menejer', 'Бренд-менеджер', 60),
  ('marketing', 'pr', 'PR mutaxassis', 'PR-специалист', 70),
  ('design', 'graphic', 'Grafik dizayner', 'Графический дизайнер', 0),
  ('design', 'interior', 'Interyer dizayneri', 'Дизайнер интерьера', 10),
  ('design', 'video', 'Videomontajchi', 'Видеомонтажёр', 20),
  ('design', 'motion', 'Motion dizayner', 'Моушн-дизайнер', 30),
  ('design', '3d', '3D vizualizator', '3D-визуализатор', 40),
  ('design', 'photographer', 'Fotograf', 'Фотограф', 50),
  ('design', 'videographer', 'Videograf', 'Видеограф', 60),
  ('finance', 'accountant', 'Buxgalter', 'Бухгалтер', 0),
  ('finance', 'chief_accountant', 'Bosh buxgalter', 'Главный бухгалтер', 10),
  ('finance', 'assistant_accountant', 'Buxgalter yordamchisi', 'Помощник бухгалтера', 20),
  ('finance', 'financier', 'Moliyachi', 'Финансист', 30),
  ('finance', 'economist', 'Iqtisodchi', 'Экономист', 40),
  ('finance', 'auditor', 'Auditor', 'Аудитор', 50),
  ('finance', 'credit', 'Kredit mutaxassisi', 'Кредитный специалист', 60),
  ('driver', 'cat_b', 'Haydovchi (B toifa)', 'Водитель (категория B)', 0),
  ('driver', 'cat_c', 'Haydovchi (C toifa)', 'Водитель (категория C)', 10),
  ('driver', 'cat_d', 'Haydovchi (D toifa)', 'Водитель (категория D)', 20),
  ('driver', 'truck', 'Yuk mashinasi haydovchisi', 'Водитель грузовика', 30),
  ('driver', 'taxi', 'Taksi haydovchisi', 'Водитель такси', 40),
  ('driver', 'personal', 'Shaxsiy haydovchi', 'Личный водитель', 50),
  ('driver', 'tractor', 'Traktorchi', 'Тракторист', 60),
  ('logistics', 'logist', 'Logist', 'Логист', 0),
  ('logistics', 'forwarder', 'Ekspeditor', 'Экспедитор', 10),
  ('logistics', 'dispatcher', 'Dispetcher', 'Диспетчер', 20),
  ('logistics', 'warehouse', 'Omborchi', 'Кладовщик', 30),
  ('logistics', 'loader', 'Yuk tashuvchi', 'Грузчик', 40),
  ('logistics', 'picker', 'Komplektovchi', 'Комплектовщик', 50),
  ('courier', 'foot', 'Piyoda kuryer', 'Пеший курьер', 0),
  ('courier', 'scooter', 'Skuter/velosiped kuryer', 'Курьер на скутере/велосипеде', 10),
  ('courier', 'auto', 'Avto kuryer', 'Автокурьер', 20),
  ('courier', 'food', 'Ovqat yetkazuvchi', 'Доставщик еды', 30),
  ('construction', 'mason', 'G''isht teruvchi', 'Каменщик', 0),
  ('construction', 'plasterer', 'Suvoqchi', 'Штукатур', 10),
  ('construction', 'tiler', 'Kafelchi', 'Плиточник', 20),
  ('construction', 'concrete', 'Betonchi', 'Бетонщик', 30),
  ('construction', 'carpenter', 'Duradgor', 'Плотник', 40),
  ('construction', 'engineer', 'Muhandis-quruvchi', 'Инженер-строитель', 50),
  ('construction', 'foreman', 'Prorab', 'Прораб', 60),
  ('construction', 'crane', 'Kranchi', 'Крановщик', 70),
  ('construction', 'laborer', 'Qora ishchi', 'Разнорабочий', 80),
  ('construction', 'roofer', 'Tomchi', 'Кровельщик', 90),
  ('craftsman', 'universal', 'Universal usta', 'Мастер на все руки', 0),
  ('craftsman', 'furniture', 'Mebel ustasi', 'Мебельщик', 10),
  ('craftsman', 'welder', 'Payvandchi', 'Сварщик', 20),
  ('craftsman', 'hvac', 'Konditsioner ustasi', 'Мастер по кондиционерам', 30),
  ('craftsman', 'painter', 'Bo''yoqchi', 'Маляр', 40),
  ('craftsman', 'drywall', 'Gipsokarton ustasi', 'Гипсокартонщик', 50),
  ('craftsman', 'appliance', 'Maishiy texnika ustasi', 'Мастер по бытовой технике', 60),
  ('craftsman', 'locksmith', 'Chilangar', 'Слесарь', 70),
  ('electrician', 'electrician', 'Elektrik', 'Электрик', 0),
  ('electrician', 'electromontage', 'Elektromontajchi', 'Электромонтажник', 10),
  ('electrician', 'electronics', 'Elektron texnik', 'Техник-электронщик', 20),
  ('electrician', 'high_voltage', 'Yuqori kuchlanish elektrigi', 'Электрик высоковольтных сетей', 30),
  ('plumber', 'plumber', 'Santexnik', 'Сантехник', 0),
  ('plumber', 'heating', 'Isitish tizimi ustasi', 'Мастер отопления', 10),
  ('plumber', 'sewage', 'Kanalizatsiya ustasi', 'Мастер канализации', 20),
  ('mechanic', 'mechanic', 'Mexanik', 'Механик', 0),
  ('mechanic', 'technician', 'Texnik', 'Техник', 10),
  ('mechanic', 'machinist', 'Stanokchi', 'Станочник', 20),
  ('mechanic', 'maintenance', 'Ta''mirlash ustasi', 'Ремонтник оборудования', 30),
  ('auto_service', 'motorist', 'Motorist', 'Моторист', 0),
  ('auto_service', 'auto_electric', 'Avtoelektrik', 'Автоэлектрик', 10),
  ('auto_service', 'chassis', 'Xodovik', 'Ходовик', 20),
  ('auto_service', 'body', 'Kuzovchi', 'Кузовщик', 30),
  ('auto_service', 'paint', 'Avto bo''yoqchi', 'Автомаляр', 40),
  ('auto_service', 'diagnost', 'Diagnost', 'Диагност', 50),
  ('auto_service', 'tire', 'Shina ustasi', 'Шиномонтажник', 60),
  ('auto_service', 'oil', 'Moy almashtiruvchi', 'Мастер по замене масла', 70),
  ('auto_service', 'detailing', 'Deteyling ustasi', 'Мастер детейлинга', 80),
  ('restaurant', 'waiter', 'Ofitsiant', 'Официант', 0),
  ('restaurant', 'bartender', 'Barmen', 'Бармен', 10),
  ('restaurant', 'barista', 'Barista', 'Бариста', 20),
  ('restaurant', 'cook', 'Oshpaz', 'Повар', 30),
  ('restaurant', 'cook_assistant', 'Oshpaz yordamchisi', 'Помощник повара', 40),
  ('restaurant', 'baker', 'Novvoy', 'Пекарь', 50),
  ('restaurant', 'confectioner', 'Qandolatchi', 'Кондитер', 60),
  ('restaurant', 'sushi', 'Sushi oshpazi', 'Сушист', 70),
  ('restaurant', 'hostess', 'Xostes', 'Хостес', 80),
  ('restaurant', 'dishwasher', 'Idish yuvuvchi', 'Посудомойщик', 90),
  ('restaurant', 'admin', 'Restoran administratori', 'Администратор ресторана', 100),
  ('restaurant', 'pizza', 'Pitsameyker', 'Пиццамейкер', 110),
  ('call_center', 'operator', 'Operator', 'Оператор', 0),
  ('call_center', 'call_center', 'Call-markaz operatori', 'Оператор колл-центра', 10),
  ('call_center', 'online', 'Onlayn konsultant', 'Онлайн-консультант', 20),
  ('call_center', 'telemarketing', 'Telemarketolog', 'Телемаркетолог', 30),
  ('office', 'administrator', 'Administrator', 'Администратор', 0),
  ('office', 'office_manager', 'Ofis-menejer', 'Офис-менеджер', 10),
  ('office', 'secretary', 'Kotib(a)', 'Секретарь', 20),
  ('office', 'manager', 'Menejer', 'Менеджер', 30),
  ('office', 'hr', 'HR menejer', 'HR-менеджер', 40),
  ('office', 'recruiter', 'Rekruter', 'Рекрутер', 50),
  ('office', 'lawyer', 'Yurist', 'Юрист', 60),
  ('office', 'project_manager', 'Loyiha menejeri', 'Проектный менеджер', 70),
  ('office', 'assistant', 'Rahbar yordamchisi', 'Помощник руководителя', 80),
  ('education', 'teacher', 'O''qituvchi', 'Учитель', 0),
  ('education', 'tutor', 'Repetitor', 'Репетитор', 10),
  ('education', 'kindergarten', 'Tarbiyachi', 'Воспитатель', 20),
  ('education', 'english', 'Ingliz tili o''qituvchisi', 'Учитель английского', 30),
  ('education', 'russian', 'Rus tili o''qituvchisi', 'Учитель русского', 40),
  ('education', 'math', 'Matematika o''qituvchisi', 'Учитель математики', 50),
  ('education', 'trainer', 'Trener', 'Тренер', 60),
  ('education', 'methodist', 'Metodist', 'Методист', 70),
  ('medicine', 'doctor', 'Shifokor', 'Врач', 0),
  ('medicine', 'nurse', 'Hamshira', 'Медсестра', 10),
  ('medicine', 'pharmacist', 'Farmatsevt', 'Фармацевт', 20),
  ('medicine', 'dentist', 'Stomatolog', 'Стоматолог', 30),
  ('medicine', 'lab', 'Laborant', 'Лаборант', 40),
  ('medicine', 'massage', 'Massajchi', 'Массажист', 50),
  ('medicine', 'caregiver', 'Qarovchi / hamshira', 'Сиделка', 60),
  ('cleaning', 'cleaner', 'Farrosh', 'Уборщик(ца)', 0),
  ('cleaning', 'housekeeper', 'Uy xizmatchisi', 'Домработница', 10),
  ('cleaning', 'nanny', 'Enaga', 'Няня', 20),
  ('cleaning', 'gardener', 'Bog''bon', 'Садовник', 30),
  ('cleaning', 'dry_cleaning', 'Kimyoviy tozalash xodimi', 'Работник химчистки', 40),
  ('security', 'guard', 'Qo''riqchi', 'Охранник', 0),
  ('security', 'security_officer', 'Xavfsizlik xodimi', 'Сотрудник безопасности', 10),
  ('security', 'cctv', 'Videokuzatuv operatori', 'Оператор видеонаблюдения', 20),
  ('security', 'bodyguard', 'Tansoqchi', 'Телохранитель', 30),
  ('sewing', 'seamstress', 'Tikuvchi', 'Швея', 0),
  ('sewing', 'cutter', 'Bichuvchi', 'Закройщик', 10),
  ('sewing', 'ironer', 'Dazmolchi', 'Утюжильщик', 20),
  ('sewing', 'knitter', 'Trikotajchi', 'Вязальщик', 30),
  ('sewing', 'designer', 'Modelyer', 'Модельер', 40),
  ('beauty', 'hairdresser', 'Sartarosh', 'Парикмахер', 0),
  ('beauty', 'barber', 'Barber', 'Барбер', 10),
  ('beauty', 'manicure', 'Manikyur ustasi', 'Мастер маникюра', 20),
  ('beauty', 'cosmetologist', 'Kosmetolog', 'Косметолог', 30),
  ('beauty', 'makeup', 'Vizajist', 'Визажист', 40),
  ('beauty', 'lashes', 'Kiprik ustasi', 'Лэшмейкер', 50),
  ('beauty', 'brows', 'Qosh ustasi', 'Бровист', 60),
  ('beauty', 'massage', 'Massajchi', 'Массажист', 70),
  ('production', 'operator', 'Stanok operatori', 'Оператор станка', 0),
  ('production', 'technologist', 'Texnolog', 'Технолог', 10),
  ('production', 'packer', 'Qadoqlovchi', 'Упаковщик', 20),
  ('production', 'qc', 'Sifat nazoratchisi', 'Контролёр качества', 30),
  ('production', 'assembler', 'Yig''uvchi', 'Сборщик', 40),
  ('production', 'shift_lead', 'Smena boshlig''i', 'Начальник смены', 50),
  ('agriculture', 'farmer', 'Fermer xodimi', 'Работник фермы', 0),
  ('agriculture', 'agronomist', 'Agronom', 'Агроном', 10),
  ('agriculture', 'vet', 'Veterinar', 'Ветеринар', 20),
  ('agriculture', 'livestock', 'Chorvador', 'Животновод', 30),
  ('agriculture', 'greenhouse', 'Issiqxona ishchisi', 'Работник теплицы', 40),
  ('other', 'other', 'Boshqa', 'Другое', 0)
) as s(category_slug, slug, name_uz, name_ru, sort_order)
join public.categories c on c.slug = s.category_slug
on conflict (category_id, slug) do update set name_uz = excluded.name_uz, name_ru = excluded.name_ru, sort_order = excluded.sort_order;

insert into public.skills (slug, name_uz, name_ru, category_id)
select s.slug, s.name_uz, s.name_ru, c.id from (values
  ('it_javascript', 'JavaScript', 'JavaScript', 'it'),
  ('it_typescript', 'TypeScript', 'TypeScript', 'it'),
  ('it_react', 'React', 'React', 'it'),
  ('it_nextjs', 'Next.js', 'Next.js', 'it'),
  ('it_nodejs', 'Node.js', 'Node.js', 'it'),
  ('it_python', 'Python', 'Python', 'it'),
  ('it_java', 'Java', 'Java', 'it'),
  ('it_php', 'PHP', 'PHP', 'it'),
  ('it_laravel', 'Laravel', 'Laravel', 'it'),
  ('it_flutter', 'Flutter', 'Flutter', 'it'),
  ('it_kotlin', 'Kotlin', 'Kotlin', 'it'),
  ('it_swift', 'Swift', 'Swift', 'it'),
  ('it_sql', 'SQL', 'SQL', 'it'),
  ('it_postgresql', 'PostgreSQL', 'PostgreSQL', 'it'),
  ('it_docker', 'Docker', 'Docker', 'it'),
  ('it_git', 'Git', 'Git', 'it'),
  ('it_figma', 'Figma', 'Figma', 'it'),
  ('it_linux', 'Linux', 'Linux', 'it'),
  ('it_csharp', 'C#', 'C#', 'it'),
  ('it_golang', 'Go', 'Go', 'it'),
  ('sales_pos', 'POS terminal', 'POS-терминал', 'sales'),
  ('sales_cash', 'Naqd pul bilan ishlash', 'Работа с наличными', 'sales'),
  ('sales_click', 'Click', 'Click', 'sales'),
  ('sales_payme', 'Payme', 'Payme', 'sales'),
  ('sales_1c', '1C', '1C', 'sales'),
  ('sales_reporting', 'Hisobot tayyorlash', 'Подготовка отчётов', 'sales'),
  ('sales_excel', 'Excel', 'Excel', 'sales'),
  ('sales_crm', 'CRM', 'CRM', 'sales'),
  ('sales_sales', 'Sotuv ko''nikmasi', 'Навыки продаж', 'sales'),
  ('sales_negotiation', 'Muzokara', 'Переговоры', 'sales'),
  ('sales_customer_service', 'Mijozlarga xizmat', 'Обслуживание клиентов', 'sales'),
  ('sales_merchandising', 'Merchandayzing', 'Мерчандайзинг', 'sales'),
  ('sales_cold_calls', 'Sovuq qo''ng''iroqlar', 'Холодные звонки', 'sales'),
  ('marketing_instagram', 'Instagram', 'Instagram', 'marketing'),
  ('marketing_telegram', 'Telegram', 'Telegram', 'marketing'),
  ('marketing_target_ads', 'Target reklama', 'Таргетированная реклама', 'marketing'),
  ('marketing_google_ads', 'Google Ads', 'Google Ads', 'marketing'),
  ('marketing_canva', 'Canva', 'Canva', 'marketing'),
  ('marketing_copywriting', 'Kopirayting', 'Копирайтинг', 'marketing'),
  ('marketing_content_plan', 'Kontent-plan', 'Контент-план', 'marketing'),
  ('marketing_analytics', 'Analitika', 'Аналитика', 'marketing'),
  ('marketing_seo', 'SEO', 'SEO', 'marketing'),
  ('marketing_capcut', 'CapCut', 'CapCut', 'marketing'),
  ('marketing_mobilography', 'Mobilografiya', 'Мобилография', 'marketing'),
  ('design_photoshop', 'Photoshop', 'Photoshop', 'design'),
  ('design_illustrator', 'Illustrator', 'Illustrator', 'design'),
  ('design_figma_d', 'Figma', 'Figma', 'design'),
  ('design_premiere', 'Premiere Pro', 'Premiere Pro', 'design'),
  ('design_after_effects', 'After Effects', 'After Effects', 'design'),
  ('design_3dsmax', '3ds Max', '3ds Max', 'design'),
  ('design_blender', 'Blender', 'Blender', 'design'),
  ('design_autocad', 'AutoCAD', 'AutoCAD', 'design'),
  ('design_corel', 'CorelDRAW', 'CorelDRAW', 'design'),
  ('design_lightroom', 'Lightroom', 'Lightroom', 'design'),
  ('finance_1c_acc', '1C Buxgalteriya', '1C Бухгалтерия', 'finance'),
  ('finance_excel_f', 'Excel (ilg''or)', 'Excel (продвинутый)', 'finance'),
  ('finance_tax', 'Soliq hisoboti', 'Налоговая отчётность', 'finance'),
  ('finance_didox', 'Didox / E-faktura', 'Didox / Электронные счета-фактуры', 'finance'),
  ('finance_payroll', 'Ish haqi hisoblash', 'Расчёт зарплаты', 'finance'),
  ('finance_ifrs', 'IFRS / XMHS', 'МСФО', 'finance'),
  ('finance_audit', 'Audit', 'Аудит', 'finance'),
  ('finance_budgeting', 'Byudjetlash', 'Бюджетирование', 'finance'),
  ('driver_license_b', 'B toifa guvohnoma', 'Права категории B', 'driver'),
  ('driver_license_c', 'C toifa guvohnoma', 'Права категории C', 'driver'),
  ('driver_license_d', 'D toifa guvohnoma', 'Права категории D', 'driver'),
  ('driver_license_e', 'E toifa guvohnoma', 'Права категории E', 'driver'),
  ('driver_own_car', 'Shaxsiy avtomobil', 'Личный автомобиль', 'driver'),
  ('driver_manual', 'Mexanika', 'Механика', 'driver'),
  ('driver_intercity', 'Shaharlararo', 'Междугородние рейсы', 'driver'),
  ('driver_yandex_go', 'Yandex Go', 'Yandex Go', 'driver'),
  ('logistics_warehouse_acc', 'Ombor hisobi', 'Складской учёт', 'logistics'),
  ('logistics_wms', 'WMS', 'WMS', 'logistics'),
  ('logistics_forklift', 'Pogruzchik boshqarish', 'Управление погрузчиком', 'logistics'),
  ('logistics_routes', 'Marshrut rejalashtirish', 'Планирование маршрутов', 'logistics'),
  ('logistics_customs', 'Bojxona rasmiylashtiruvi', 'Таможенное оформление', 'logistics'),
  ('logistics_excel_l', 'Excel', 'Excel', 'logistics'),
  ('courier_scooter', 'Skuter', 'Скутер', 'courier'),
  ('courier_bicycle', 'Velosiped', 'Велосипед', 'courier'),
  ('courier_own_car_c', 'Shaxsiy avtomobil', 'Личный автомобиль', 'courier'),
  ('courier_city_knowledge', 'Shaharni yaxshi bilish', 'Знание города', 'courier'),
  ('courier_yandex_eats', 'Yandex Eats / Uzum Tezkor', 'Yandex Eats / Uzum Tezkor', 'courier'),
  ('construction_masonry', 'G''isht terish', 'Кладка кирпича', 'construction'),
  ('construction_plastering', 'Suvoq', 'Штукатурка', 'construction'),
  ('construction_tiling', 'Kafel yotqizish', 'Укладка плитки', 'construction'),
  ('construction_concrete_w', 'Beton ishlari', 'Бетонные работы', 'construction'),
  ('construction_drawings', 'Chizma o''qish', 'Чтение чертежей', 'construction'),
  ('construction_laminate', 'Laminat yotqizish', 'Укладка ламината', 'construction'),
  ('construction_facade', 'Fasad ishlari', 'Фасадные работы', 'construction'),
  ('construction_scaffolding', 'Iskala', 'Строительные леса', 'construction'),
  ('craftsman_welding', 'Payvandlash', 'Сварка', 'craftsman'),
  ('craftsman_argon', 'Argon payvandlash', 'Аргонная сварка', 'craftsman'),
  ('craftsman_furniture_m', 'Mebel yig''ish', 'Сборка мебели', 'craftsman'),
  ('craftsman_drywall_s', 'Gipsokarton', 'Гипсокартон', 'craftsman'),
  ('craftsman_painting', 'Bo''yash', 'Покраска', 'craftsman'),
  ('craftsman_hvac_s', 'Konditsioner o''rnatish', 'Установка кондиционеров', 'craftsman'),
  ('craftsman_appliance_r', 'Maishiy texnika ta''miri', 'Ремонт бытовой техники', 'craftsman'),
  ('electrician_wiring', 'Elektr simlarini tortish', 'Электропроводка', 'electrician'),
  ('electrician_panel', 'Elektr shchit yig''ish', 'Сборка электрощитов', 'electrician'),
  ('electrician_automation', 'Avtomatika', 'Автоматика', 'electrician'),
  ('electrician_high_v', 'Yuqori kuchlanish', 'Высокое напряжение', 'electrician'),
  ('electrician_plc', 'PLC', 'ПЛК', 'electrician'),
  ('electrician_schematics', 'Sxema o''qish', 'Чтение схем', 'electrician'),
  ('plumber_pipes', 'Quvur o''tkazish', 'Монтаж труб', 'plumber'),
  ('plumber_heating_s', 'Isitish tizimi', 'Система отопления', 'plumber'),
  ('plumber_boiler', 'Kotyol o''rnatish', 'Установка котлов', 'plumber'),
  ('plumber_sanitary', 'Santexnika o''rnatish', 'Установка сантехники', 'plumber'),
  ('plumber_ppr', 'PPR payvandlash', 'Пайка PPR', 'plumber'),
  ('mechanic_lathe', 'Tokarlik', 'Токарные работы', 'mechanic'),
  ('mechanic_milling', 'Frezerlik', 'Фрезерные работы', 'mechanic'),
  ('mechanic_hydraulics', 'Gidravlika', 'Гидравлика', 'mechanic'),
  ('mechanic_cnc', 'CNC', 'ЧПУ', 'mechanic'),
  ('mechanic_maintenance_s', 'Uskunalar ta''miri', 'Ремонт оборудования', 'mechanic'),
  ('auto_service_engine', 'Dvigatel ta''miri', 'Ремонт двигателя', 'auto_service'),
  ('auto_service_auto_el', 'Avtoelektrika', 'Автоэлектрика', 'auto_service'),
  ('auto_service_suspension', 'Xodovoy ta''miri', 'Ремонт ходовой', 'auto_service'),
  ('auto_service_bodywork', 'Kuzov ishlari', 'Кузовные работы', 'auto_service'),
  ('auto_service_auto_paint', 'Avto bo''yash', 'Автопокраска', 'auto_service'),
  ('auto_service_diagnostics', 'Kompyuter diagnostikasi', 'Компьютерная диагностика', 'auto_service'),
  ('auto_service_tire_s', 'Shinamontaj', 'Шиномонтаж', 'auto_service'),
  ('auto_service_chevrolet', 'Chevrolet', 'Chevrolet', 'auto_service'),
  ('auto_service_mercedes', 'Mercedes', 'Mercedes', 'auto_service'),
  ('auto_service_bmw', 'BMW', 'BMW', 'auto_service'),
  ('auto_service_toyota', 'Toyota', 'Toyota', 'auto_service'),
  ('auto_service_kia_hyundai', 'Kia / Hyundai', 'Kia / Hyundai', 'auto_service'),
  ('auto_service_electric_cars', 'Elektromobillar', 'Электромобили', 'auto_service'),
  ('restaurant_uzbek_cuisine', 'O''zbek taomlari', 'Узбекская кухня', 'restaurant'),
  ('restaurant_european', 'Yevropa taomlari', 'Европейская кухня', 'restaurant'),
  ('restaurant_asian', 'Osiyo taomlari', 'Азиатская кухня', 'restaurant'),
  ('restaurant_coffee', 'Kofe tayyorlash', 'Приготовление кофе', 'restaurant'),
  ('restaurant_latte_art', 'Latte-art', 'Латте-арт', 'restaurant'),
  ('restaurant_cocktails', 'Kokteyllar', 'Коктейли', 'restaurant'),
  ('restaurant_r_keeper', 'R-Keeper / iiko', 'R-Keeper / iiko', 'restaurant'),
  ('restaurant_service', 'Xizmat ko''rsatish standarti', 'Стандарты сервиса', 'restaurant'),
  ('restaurant_haccp', 'Sanitariya (HACCP)', 'Санитария (HACCP)', 'restaurant'),
  ('restaurant_baking', 'Non yopish', 'Выпечка', 'restaurant'),
  ('call_center_phone_etiquette', 'Telefon etikasi', 'Телефонный этикет', 'call_center'),
  ('call_center_crm_c', 'CRM', 'CRM', 'call_center'),
  ('call_center_typing', 'Tez yozish', 'Быстрая печать', 'call_center'),
  ('call_center_objections', 'E''tirozlar bilan ishlash', 'Работа с возражениями', 'call_center'),
  ('call_center_bitrix', 'Bitrix24', 'Bitrix24', 'call_center'),
  ('call_center_amocrm', 'amoCRM', 'amoCRM', 'call_center'),
  ('office_ms_office', 'MS Office', 'MS Office', 'office'),
  ('office_google_docs', 'Google Docs', 'Google Docs', 'office'),
  ('office_document_flow', 'Hujjat aylanishi', 'Документооборот', 'office'),
  ('office_recruiting', 'Rekruting', 'Рекрутинг', 'office'),
  ('office_labor_law', 'Mehnat qonunchiligi', 'Трудовое законодательство', 'office'),
  ('office_planning', 'Rejalashtirish', 'Планирование', 'office'),
  ('office_presentations', 'Prezentatsiya', 'Презентации', 'office'),
  ('office_business_correspondence', 'Ish yozishmalari', 'Деловая переписка', 'office'),
  ('education_ielts', 'IELTS', 'IELTS', 'education'),
  ('education_cefr', 'CEFR', 'CEFR', 'education'),
  ('education_methodology', 'Metodika', 'Методика', 'education'),
  ('education_online_teaching', 'Onlayn dars', 'Онлайн-обучение', 'education'),
  ('education_kids', 'Bolalar bilan ishlash', 'Работа с детьми', 'education'),
  ('education_curriculum', 'Dastur tuzish', 'Составление программы', 'education'),
  ('medicine_injections', 'In''yeksiya', 'Инъекции', 'medicine'),
  ('medicine_first_aid', 'Birinchi yordam', 'Первая помощь', 'medicine'),
  ('medicine_diploma', 'Tibbiy diplom', 'Медицинский диплом', 'medicine'),
  ('medicine_license', 'Litsenziya', 'Лицензия', 'medicine'),
  ('medicine_patient_care', 'Bemor parvarishi', 'Уход за больными', 'medicine'),
  ('medicine_pharmacy', 'Dorixona ishi', 'Аптечное дело', 'medicine'),
  ('cleaning_cleaning_s', 'Professional tozalash', 'Профессиональная уборка', 'cleaning'),
  ('cleaning_chemicals', 'Kimyoviy vositalar', 'Химические средства', 'cleaning'),
  ('cleaning_childcare', 'Bola parvarishi', 'Уход за детьми', 'cleaning'),
  ('cleaning_cooking_h', 'Ovqat tayyorlash', 'Приготовление еды', 'cleaning'),
  ('cleaning_elderly_care', 'Keksalar parvarishi', 'Уход за пожилыми', 'cleaning'),
  ('security_guard_license', 'Qo''riqlash guvohnomasi', 'Лицензия охранника', 'security'),
  ('security_cctv_s', 'Videokuzatuv', 'Видеонаблюдение', 'security'),
  ('security_martial_arts', 'Jismoniy tayyorgarlik', 'Физическая подготовка', 'security'),
  ('security_access_control', 'Kirish nazorati', 'Контроль доступа', 'security'),
  ('sewing_industrial_machine', 'Sanoat mashinasi', 'Промышленная машина', 'sewing'),
  ('sewing_overlock', 'Overlok', 'Оверлок', 'sewing'),
  ('sewing_cutting', 'Bichish', 'Раскрой', 'sewing'),
  ('sewing_pattern', 'Andoza', 'Лекала', 'sewing'),
  ('sewing_embroidery', 'Kashta', 'Вышивка', 'sewing'),
  ('beauty_haircut', 'Soch olish', 'Стрижка', 'beauty'),
  ('beauty_coloring', 'Soch bo''yash', 'Окрашивание', 'beauty'),
  ('beauty_manicure_s', 'Manikyur', 'Маникюр', 'beauty'),
  ('beauty_pedicure', 'Pedikyur', 'Педикюр', 'beauty'),
  ('beauty_gel', 'Gel-lak', 'Гель-лак', 'beauty'),
  ('beauty_makeup_s', 'Makiyaj', 'Макияж', 'beauty'),
  ('beauty_lash_ext', 'Kiprik uzaytirish', 'Наращивание ресниц', 'beauty'),
  ('beauty_brow_s', 'Qosh shakllantirish', 'Оформление бровей', 'beauty'),
  ('production_machine_op', 'Stanok boshqarish', 'Управление станком', 'production'),
  ('production_quality', 'Sifat nazorati', 'Контроль качества', 'production'),
  ('production_packing', 'Qadoqlash', 'Упаковка', 'production'),
  ('production_assembly', 'Yig''ish', 'Сборка', 'production'),
  ('production_safety', 'Mehnat xavfsizligi', 'Техника безопасности', 'production'),
  ('agriculture_tractor_s', 'Traktor', 'Трактор', 'agriculture'),
  ('agriculture_irrigation', 'Sug''orish', 'Орошение', 'agriculture'),
  ('agriculture_livestock_s', 'Chorva parvarishi', 'Уход за скотом', 'agriculture'),
  ('agriculture_greenhouse_s', 'Issiqxona', 'Теплица', 'agriculture'),
  ('agriculture_harvest', 'Hosil yig''ish', 'Сбор урожая', 'agriculture'),
  ('general_uzbek', 'O''zbek tili', 'Узбекский язык', null),
  ('general_russian', 'Rus tili', 'Русский язык', null),
  ('general_english', 'Ingliz tili', 'Английский язык', null),
  ('general_teamwork', 'Jamoada ishlash', 'Работа в команде', null),
  ('general_communication', 'Muloqot', 'Коммуникабельность', null),
  ('general_responsibility', 'Mas''uliyat', 'Ответственность', null),
  ('general_computer', 'Kompyuter savodxonligi', 'Компьютерная грамотность', null),
  ('general_smartphone', 'Smartfon bilan ishlash', 'Работа со смартфоном', null),
  ('general_time_management', 'Vaqtni boshqarish', 'Тайм-менеджмент', null),
  ('general_leadership', 'Liderlik', 'Лидерство', null),
  ('general_stress', 'Stressga chidamlilik', 'Стрессоустойчивость', null)
) as s(slug, name_uz, name_ru, category_slug)
left join public.categories c on c.slug = s.category_slug
on conflict (slug) do update set name_uz = excluded.name_uz, name_ru = excluded.name_ru, category_id = excluded.category_id;

insert into public.regions (slug, name_uz, name_ru, sort_order) values
  ('tashkent_city', 'Toshkent shahri', 'Ташкент', 0),
  ('tashkent_region', 'Toshkent viloyati', 'Ташкентская область', 10),
  ('samarkand', 'Samarqand', 'Самарканд', 20),
  ('bukhara', 'Buxoro', 'Бухара', 30),
  ('andijan', 'Andijon', 'Андижан', 40),
  ('namangan', 'Namangan', 'Наманган', 50),
  ('fergana', 'Farg''ona', 'Фергана', 60),
  ('kashkadarya', 'Qashqadaryo', 'Кашкадарья', 70),
  ('surkhandarya', 'Surxondaryo', 'Сурхандарья', 80),
  ('jizzakh', 'Jizzax', 'Джизак', 90),
  ('syrdarya', 'Sirdaryo', 'Сырдарья', 100),
  ('navoi', 'Navoiy', 'Навои', 110),
  ('khorezm', 'Xorazm', 'Хорезм', 120),
  ('karakalpakstan', 'Qoraqalpog''iston', 'Каракалпакстан', 130)
on conflict (slug) do update set name_uz = excluded.name_uz, name_ru = excluded.name_ru, sort_order = excluded.sort_order;

insert into public.districts (region_id, slug, name_uz, name_ru, lat, lng, sort_order)
select r.id, d.slug, d.name_uz, d.name_ru, d.lat, d.lng, d.sort_order from (values
  ('tashkent_city', 'bektemir', 'Bektemir', 'Бектемир', 41.2103, 69.3369, 0),
  ('tashkent_city', 'chilonzor', 'Chilonzor', 'Чиланзар', 41.2753, 69.204, 10),
  ('tashkent_city', 'mirobod', 'Mirobod', 'Мирабад', 41.287, 69.287, 20),
  ('tashkent_city', 'mirzo_ulugbek', 'Mirzo Ulug''bek', 'Мирзо-Улугбек', 41.335, 69.335, 30),
  ('tashkent_city', 'olmazor', 'Olmazor', 'Алмазар', 41.349, 69.211, 40),
  ('tashkent_city', 'sergeli', 'Sergeli', 'Сергели', 41.223, 69.222, 50),
  ('tashkent_city', 'shayxontohur', 'Shayxontohur', 'Шайхантахур', 41.322, 69.232, 60),
  ('tashkent_city', 'uchtepa', 'Uchtepa', 'Учтепа', 41.293, 69.172, 70),
  ('tashkent_city', 'yakkasaroy', 'Yakkasaroy', 'Яккасарай', 41.286, 69.247, 80),
  ('tashkent_city', 'yashnobod', 'Yashnobod', 'Яшнабад', 41.293, 69.323, 90),
  ('tashkent_city', 'yunusobod', 'Yunusobod', 'Юнусабад', 41.364, 69.286, 100),
  ('tashkent_city', 'yangihayot', 'Yangihayot', 'Янгихаёт', 41.208, 69.268, 110),
  ('tashkent_region', 'nurafshon', 'Nurafshon', 'Нурафшон', 41.044, 69.358, 0),
  ('tashkent_region', 'angren', 'Angren', 'Ангрен', 41.017, 70.143, 10),
  ('tashkent_region', 'bekobod', 'Bekobod', 'Бекабад', 40.221, 69.27, 20),
  ('tashkent_region', 'boka', 'Bo''ka', 'Бука', 40.81, 69.199, 30),
  ('tashkent_region', 'bostonliq', 'Bo''stonliq', 'Бостанлык', 41.59, 69.99, 40),
  ('tashkent_region', 'chinoz', 'Chinoz', 'Чиназ', 40.937, 68.762, 50),
  ('tashkent_region', 'chirchiq', 'Chirchiq', 'Чирчик', 41.469, 69.582, 60),
  ('tashkent_region', 'ohangaron', 'Ohangaron', 'Ахангаран', 40.907, 69.641, 70),
  ('tashkent_region', 'olmaliq', 'Olmaliq', 'Алмалык', 40.844, 69.598, 80),
  ('tashkent_region', 'oqqorgon', 'Oqqo''rg''on', 'Аккурган', 40.857, 69.045, 90),
  ('tashkent_region', 'parkent', 'Parkent', 'Паркент', 41.294, 69.676, 100),
  ('tashkent_region', 'piskent', 'Piskent', 'Пскент', 40.904, 69.349, 110),
  ('tashkent_region', 'qibray', 'Qibray', 'Кибрай', 41.39, 69.465, 120),
  ('tashkent_region', 'quyichirchiq', 'Quyichirchiq', 'Куйичирчик', 40.99, 69.07, 130),
  ('tashkent_region', 'ortachirchiq', 'O''rtachirchiq', 'Уртачирчик', 41.14, 69.34, 140),
  ('tashkent_region', 'yangiyol', 'Yangiyo''l', 'Янгиюль', 41.112, 69.047, 150),
  ('tashkent_region', 'yuqorichirchiq', 'Yuqorichirchiq', 'Юкоричирчик', 41.24, 69.47, 160),
  ('tashkent_region', 'zangiota', 'Zangiota', 'Зангиата', 41.2, 69.12, 170),
  ('samarkand', 'samarkand_city', 'Samarqand shahri', 'г. Самарканд', 39.654, 66.96, 0),
  ('samarkand', 'bulungur', 'Bulung''ur', 'Булунгур', 39.76, 67.27, 10),
  ('samarkand', 'ishtixon', 'Ishtixon', 'Иштыхан', 39.97, 66.49, 20),
  ('samarkand', 'jomboy', 'Jomboy', 'Джамбай', 39.7, 67.09, 30),
  ('samarkand', 'kattaqorgon', 'Kattaqo''rg''on', 'Каттакурган', 39.9, 66.26, 40),
  ('samarkand', 'narpay', 'Narpay', 'Нарпай', 39.96, 66.05, 50),
  ('samarkand', 'nurobod', 'Nurobod', 'Нурабад', 39.77, 66.15, 60),
  ('samarkand', 'oqdaryo', 'Oqdaryo', 'Акдарья', 39.84, 66.75, 70),
  ('samarkand', 'pastdargom', 'Pastdarg''om', 'Пастдаргом', 39.55, 66.7, 80),
  ('samarkand', 'paxtachi', 'Paxtachi', 'Пахтачи', 40.05, 65.9, 90),
  ('samarkand', 'payariq', 'Payariq', 'Пайарык', 39.99, 66.85, 100),
  ('samarkand', 'qoshrabot', 'Qo''shrabot', 'Кошрабад', 40.24, 66.67, 110),
  ('samarkand', 'toyloq', 'Toyloq', 'Тайлак', 39.6, 67.05, 120),
  ('samarkand', 'urgut', 'Urgut', 'Ургут', 39.4, 67.24, 130),
  ('bukhara', 'bukhara_city', 'Buxoro shahri', 'г. Бухара', 39.768, 64.421, 0),
  ('bukhara', 'kogon', 'Kogon', 'Каган', 39.72, 64.55, 10),
  ('bukhara', 'gijduvon', 'G''ijduvon', 'Гиждуван', 40.1, 64.68, 20),
  ('bukhara', 'jondor', 'Jondor', 'Жондор', 39.73, 64.19, 30),
  ('bukhara', 'olot', 'Olot', 'Алат', 39.42, 63.8, 40),
  ('bukhara', 'peshku', 'Peshku', 'Пешку', 40.24, 64.12, 50),
  ('bukhara', 'qorakol', 'Qorako''l', 'Каракуль', 39.5, 63.85, 60),
  ('bukhara', 'qorovulbozor', 'Qorovulbozor', 'Караулбазар', 39.5, 64.8, 70),
  ('bukhara', 'romitan', 'Romitan', 'Ромитан', 39.93, 64.38, 80),
  ('bukhara', 'shofirkon', 'Shofirkon', 'Шафиркан', 40.12, 64.5, 90),
  ('bukhara', 'vobkent', 'Vobkent', 'Вабкент', 40.03, 64.51, 100),
  ('andijan', 'andijan_city', 'Andijon shahri', 'г. Андижан', 40.783, 72.344, 0),
  ('andijan', 'asaka', 'Asaka', 'Асака', 40.64, 72.24, 10),
  ('andijan', 'baliqchi', 'Baliqchi', 'Балыкчи', 40.88, 71.86, 20),
  ('andijan', 'boz', 'Bo''z', 'Боз', 40.73, 71.92, 30),
  ('andijan', 'buloqboshi', 'Buloqboshi', 'Булакбаши', 40.63, 72.47, 40),
  ('andijan', 'izboskan', 'Izboskan', 'Избаскан', 40.91, 72.15, 50),
  ('andijan', 'jalaquduq', 'Jalaquduq', 'Джалакудук', 40.73, 72.63, 60),
  ('andijan', 'marhamat', 'Marhamat', 'Мархамат', 40.48, 72.32, 70),
  ('andijan', 'oltinkol', 'Oltinko''l', 'Алтынкуль', 40.79, 72.15, 80),
  ('andijan', 'paxtaobod', 'Paxtaobod', 'Пахтаабад', 40.94, 72.48, 90),
  ('andijan', 'qorgontepa', 'Qo''rg''ontepa', 'Кургантепа', 40.73, 72.76, 100),
  ('andijan', 'shahrixon', 'Shahrixon', 'Шахрихан', 40.71, 72.05, 110),
  ('andijan', 'ulugnor', 'Ulug''nor', 'Улугнор', 40.79, 71.69, 120),
  ('andijan', 'xojaobod', 'Xo''jaobod', 'Ходжаабад', 40.67, 72.56, 130),
  ('andijan', 'xonobod', 'Xonobod', 'Ханабад', 40.8, 72.97, 140),
  ('namangan', 'namangan_city', 'Namangan shahri', 'г. Наманган', 40.998, 71.673, 0),
  ('namangan', 'chortoq', 'Chortoq', 'Чартак', 41.07, 71.82, 10),
  ('namangan', 'chust', 'Chust', 'Чуст', 41.0, 71.24, 20),
  ('namangan', 'kosonsoy', 'Kosonsoy', 'Касансай', 41.25, 71.55, 30),
  ('namangan', 'mingbuloq', 'Mingbuloq', 'Мингбулак', 40.81, 71.21, 40),
  ('namangan', 'norin', 'Norin', 'Нарын', 40.92, 71.78, 50),
  ('namangan', 'pop', 'Pop', 'Пап', 40.87, 71.11, 60),
  ('namangan', 'toraqorgon', 'To''raqo''rg''on', 'Туракурган', 41.0, 71.51, 70),
  ('namangan', 'uchqorgon', 'Uchqo''rg''on', 'Учкурган', 41.11, 72.08, 80),
  ('namangan', 'uychi', 'Uychi', 'Уйчи', 41.08, 71.93, 90),
  ('namangan', 'yangiqorgon', 'Yangiqo''rg''on', 'Янгикурган', 41.19, 71.73, 100),
  ('fergana', 'fergana_city', 'Farg''ona shahri', 'г. Фергана', 40.386, 71.786, 0),
  ('fergana', 'margilan', 'Marg''ilon', 'Маргилан', 40.47, 71.72, 10),
  ('fergana', 'kokand', 'Qo''qon', 'Коканд', 40.53, 70.94, 20),
  ('fergana', 'quvasoy', 'Quvasoy', 'Кувасай', 40.3, 71.98, 30),
  ('fergana', 'beshariq', 'Beshariq', 'Бешарык', 40.43, 70.61, 40),
  ('fergana', 'bagdod', 'Bag''dod', 'Багдад', 40.49, 71.22, 50),
  ('fergana', 'buvayda', 'Buvayda', 'Бувайда', 40.63, 71.05, 60),
  ('fergana', 'dangara', 'Dang''ara', 'Дангара', 40.59, 70.9, 70),
  ('fergana', 'furqat', 'Furqat', 'Фуркат', 40.5, 71.08, 80),
  ('fergana', 'oltiariq', 'Oltiariq', 'Алтыарык', 40.39, 71.48, 90),
  ('fergana', 'qoshtepa', 'Qo''shtepa', 'Куштепа', 40.49, 71.61, 100),
  ('fergana', 'rishton', 'Rishton', 'Риштан', 40.36, 71.28, 110),
  ('fergana', 'sox', 'So''x', 'Сох', 39.96, 71.13, 120),
  ('fergana', 'toshloq', 'Toshloq', 'Ташлак', 40.49, 71.75, 130),
  ('fergana', 'uchkoprik', 'Uchko''prik', 'Учкуприк', 40.53, 71.07, 140),
  ('fergana', 'yozyovon', 'Yozyovon', 'Язъяван', 40.66, 71.72, 150),
  ('fergana', 'ozbekiston', 'O''zbekiston', 'Узбекистан', 40.47, 71.36, 160),
  ('kashkadarya', 'karshi', 'Qarshi', 'Карши', 38.86, 65.789, 0),
  ('kashkadarya', 'shahrisabz', 'Shahrisabz', 'Шахрисабз', 39.05, 66.83, 10),
  ('kashkadarya', 'guzor', 'G''uzor', 'Гузар', 38.62, 66.25, 20),
  ('kashkadarya', 'dehqonobod', 'Dehqonobod', 'Дехканабад', 38.34, 66.5, 30),
  ('kashkadarya', 'kasbi', 'Kasbi', 'Касби', 38.95, 65.56, 40),
  ('kashkadarya', 'kitob', 'Kitob', 'Китаб', 39.12, 66.88, 50),
  ('kashkadarya', 'koson', 'Koson', 'Касан', 39.04, 65.59, 60),
  ('kashkadarya', 'mirishkor', 'Mirishkor', 'Миришкор', 38.8, 65.36, 70),
  ('kashkadarya', 'muborak', 'Muborak', 'Мубарек', 39.26, 65.16, 80),
  ('kashkadarya', 'nishon', 'Nishon', 'Нишан', 38.63, 65.68, 90),
  ('kashkadarya', 'qamashi', 'Qamashi', 'Камаши', 38.82, 66.47, 100),
  ('kashkadarya', 'chiroqchi', 'Chiroqchi', 'Чиракчи', 39.03, 66.57, 110),
  ('kashkadarya', 'yakkabog', 'Yakkabog''', 'Яккабаг', 38.97, 66.66, 120),
  ('surkhandarya', 'termez', 'Termiz', 'Термез', 37.224, 67.278, 0),
  ('surkhandarya', 'angor', 'Angor', 'Ангор', 37.49, 67.13, 10),
  ('surkhandarya', 'boysun', 'Boysun', 'Байсун', 38.2, 67.2, 20),
  ('surkhandarya', 'denov', 'Denov', 'Денау', 38.27, 67.9, 30),
  ('surkhandarya', 'jarqorgon', 'Jarqo''rg''on', 'Джаркурган', 37.51, 67.42, 40),
  ('surkhandarya', 'muzrabot', 'Muzrabot', 'Музрабад', 37.45, 67.0, 50),
  ('surkhandarya', 'oltinsoy', 'Oltinsoy', 'Алтынсай', 38.12, 67.63, 60),
  ('surkhandarya', 'qiziriq', 'Qiziriq', 'Кизирик', 37.8, 67.44, 70),
  ('surkhandarya', 'qumqorgon', 'Qumqo''rg''on', 'Кумкурган', 37.83, 67.57, 80),
  ('surkhandarya', 'sariosiyo', 'Sariosiyo', 'Сариасия', 38.41, 67.95, 90),
  ('surkhandarya', 'sherobod', 'Sherobod', 'Шерабад', 37.67, 67.0, 100),
  ('surkhandarya', 'shorchi', 'Sho''rchi', 'Шурчи', 37.99, 67.79, 110),
  ('surkhandarya', 'uzun', 'Uzun', 'Узун', 38.3, 68.0, 120),
  ('surkhandarya', 'bandixon', 'Bandixon', 'Бандихан', 37.88, 67.7, 130),
  ('jizzakh', 'jizzakh_city', 'Jizzax shahri', 'г. Джизак', 40.116, 67.842, 0),
  ('jizzakh', 'arnasoy', 'Arnasoy', 'Арнасай', 40.67, 67.9, 10),
  ('jizzakh', 'baxmal', 'Baxmal', 'Бахмал', 39.83, 67.95, 20),
  ('jizzakh', 'dostlik', 'Do''stlik', 'Дустлик', 40.52, 68.04, 30),
  ('jizzakh', 'forish', 'Forish', 'Фариш', 40.55, 66.74, 40),
  ('jizzakh', 'gallaorol', 'G''allaorol', 'Галляарал', 40.02, 67.59, 50),
  ('jizzakh', 'mirzachol', 'Mirzacho''l', 'Мирзачуль', 40.46, 68.41, 60),
  ('jizzakh', 'paxtakor', 'Paxtakor', 'Пахтакор', 40.32, 67.96, 70),
  ('jizzakh', 'sharof_rashidov', 'Sharof Rashidov', 'Шараф Рашидов', 40.2, 67.8, 80),
  ('jizzakh', 'yangiobod', 'Yangiobod', 'Янгиабад', 40.05, 68.12, 90),
  ('jizzakh', 'zafarobod', 'Zafarobod', 'Зафарабад', 40.44, 68.33, 100),
  ('jizzakh', 'zarbdor', 'Zarbdor', 'Зарбдар', 40.4, 68.2, 110),
  ('jizzakh', 'zomin', 'Zomin', 'Заамин', 39.96, 68.4, 120),
  ('syrdarya', 'guliston', 'Guliston', 'Гулистан', 40.49, 68.78, 0),
  ('syrdarya', 'yangiyer', 'Yangiyer', 'Янгиер', 40.27, 68.82, 10),
  ('syrdarya', 'shirin', 'Shirin', 'Ширин', 40.23, 69.1, 20),
  ('syrdarya', 'boyovut', 'Boyovut', 'Баяут', 40.37, 68.93, 30),
  ('syrdarya', 'mirzaobod', 'Mirzaobod', 'Мирзаабад', 40.58, 68.62, 40),
  ('syrdarya', 'oqoltin', 'Oqoltin', 'Акалтын', 40.53, 68.52, 50),
  ('syrdarya', 'sardoba', 'Sardoba', 'Сардоба', 40.52, 68.3, 60),
  ('syrdarya', 'sayxunobod', 'Sayxunobod', 'Сайхунабад', 40.74, 68.73, 70),
  ('syrdarya', 'sirdaryo', 'Sirdaryo', 'Сырдарья', 40.84, 68.66, 80),
  ('syrdarya', 'xovos', 'Xovos', 'Хавас', 40.21, 68.82, 90),
  ('navoi', 'navoi_city', 'Navoiy shahri', 'г. Навои', 40.084, 65.379, 0),
  ('navoi', 'zarafshon', 'Zarafshon', 'Зарафшан', 41.58, 64.2, 10),
  ('navoi', 'gozgon', 'G''ozg''on', 'Газган', 40.12, 65.55, 20),
  ('navoi', 'karmana', 'Karmana', 'Кармана', 40.13, 65.35, 30),
  ('navoi', 'konimex', 'Konimex', 'Канимех', 40.29, 65.13, 40),
  ('navoi', 'navbahor', 'Navbahor', 'Навбахор', 40.22, 65.63, 50),
  ('navoi', 'nurota', 'Nurota', 'Нурата', 40.56, 65.69, 60),
  ('navoi', 'qiziltepa', 'Qiziltepa', 'Кызылтепа', 40.03, 64.85, 70),
  ('navoi', 'tomdi', 'Tomdi', 'Тамды', 41.58, 64.9, 80),
  ('navoi', 'uchquduq', 'Uchquduq', 'Учкудук', 42.16, 63.56, 90),
  ('navoi', 'xatirchi', 'Xatirchi', 'Хатырчи', 40.16, 65.83, 100),
  ('khorezm', 'urgench', 'Urganch', 'Ургенч', 41.55, 60.63, 0),
  ('khorezm', 'khiva', 'Xiva', 'Хива', 41.38, 60.36, 10),
  ('khorezm', 'bogot', 'Bog''ot', 'Багат', 41.32, 60.86, 20),
  ('khorezm', 'gurlan', 'Gurlan', 'Гурлен', 41.84, 60.39, 30),
  ('khorezm', 'hazorasp', 'Hazorasp', 'Хазарасп', 41.32, 61.07, 40),
  ('khorezm', 'qoshkopir', 'Qo''shko''pir', 'Кошкупыр', 41.53, 60.35, 50),
  ('khorezm', 'shovot', 'Shovot', 'Шават', 41.67, 60.3, 60),
  ('khorezm', 'tuproqqala', 'Tuproqqal''a', 'Тупроккала', 41.65, 60.5, 70),
  ('khorezm', 'xonqa', 'Xonqa', 'Ханка', 41.47, 60.81, 80),
  ('khorezm', 'yangiariq', 'Yangiariq', 'Янгиарык', 41.36, 60.59, 90),
  ('khorezm', 'yangibozor', 'Yangibozor', 'Янгибазар', 41.74, 60.71, 100),
  ('karakalpakstan', 'nukus', 'Nukus', 'Нукус', 42.46, 59.61, 0),
  ('karakalpakstan', 'amudaryo', 'Amudaryo', 'Амударья', 42.13, 60.03, 10),
  ('karakalpakstan', 'beruniy', 'Beruniy', 'Беруни', 41.69, 60.75, 20),
  ('karakalpakstan', 'chimboy', 'Chimboy', 'Чимбай', 42.94, 59.78, 30),
  ('karakalpakstan', 'ellikqala', 'Ellikqal''a', 'Элликкала', 41.9, 60.8, 40),
  ('karakalpakstan', 'kegeyli', 'Kegeyli', 'Кегейли', 42.77, 59.61, 50),
  ('karakalpakstan', 'moynoq', 'Mo''ynoq', 'Муйнак', 43.77, 59.02, 60),
  ('karakalpakstan', 'qanlikol', 'Qanliko''l', 'Канлыкуль', 42.8, 59.02, 70),
  ('karakalpakstan', 'qongirot', 'Qo''ng''irot', 'Кунград', 43.05, 58.85, 80),
  ('karakalpakstan', 'qoraozak', 'Qorao''zak', 'Караузяк', 43.01, 60.02, 90),
  ('karakalpakstan', 'shumanay', 'Shumanay', 'Шуманай', 42.62, 58.9, 100),
  ('karakalpakstan', 'taxtakopir', 'Taxtako''pir', 'Тахтакупыр', 43.02, 60.6, 110),
  ('karakalpakstan', 'tortkol', 'To''rtko''l', 'Турткуль', 41.55, 61.0, 120),
  ('karakalpakstan', 'xojayli', 'Xo''jayli', 'Ходжейли', 42.4, 59.45, 130),
  ('karakalpakstan', 'bozatov', 'Bo''zatov', 'Бозатау', 43.2, 59.5, 140),
  ('karakalpakstan', 'taxiatosh', 'Taxiatosh', 'Тахиаташ', 42.33, 59.6, 150)
) as d(region_slug, slug, name_uz, name_ru, lat, lng, sort_order)
join public.regions r on r.slug = d.region_slug
on conflict (region_id, slug) do update set name_uz = excluded.name_uz, name_ru = excluded.name_ru, lat = excluded.lat, lng = excluded.lng, sort_order = excluded.sort_order;
